### ISSUE TITLE
When I execute the command“python server.py”, the interface does not show the image, 404 error

### ISSUE THREAD

**Issue by meng8407** [slymane/vlslice#8]
![2024-01-09 10-23-12屏幕截图](https://github.com/slymane/vlslice/assets/69879311/79bf8ffc-3721-4db0-bc82-126e1095cfa1)
![2024-01-09 10-23-36屏幕截图](https://github.com/slymane/vlslice/assets/69879311/29119def-922c-4fc6-99d6-4f0e9ca0a6e1)

**Comment by slymane** [comment]
Hi @meng8407, after cloning the repository fresh and setting up according to the README, everything seems to be functioning fine. This error is likely due to a file being located in the incorrect location. Can you please verify that your repository is in the following structure?

```./
├── README.md
└── vlslice/
    ├── client/
    └── server/
        ├── config.yml
        ├── models/
        ├── server.py
        ├── static/
        │   ├── embs.npy
        │   ├── images/
        │   │   ├── 000000.jpg
        │   │   ├── 000001.jpg
        │   │   ├── ...
        │   │   ├── 999999.jpg
        │   ├── imgs.npy
        │   └── lbls.npy
        └── utils.py
```

Additionally, when executing `python server.py`, please ensure you are at `vlslice/vlslice/server/` and not accidentally calling the command like  `python server/server.py`.

**Comment by meng8407** [comment]
> 你好@meng8407，在重新克隆存储库并根据自述文件进行设置后，一切似乎都运行良好。此错误可能是由于文件位于不正确的位置造成的。您能否验证您的存储库是否采用以下结构？
> 
> ```
> vlslice/
> ├── README.md
> └── vlslice/
>     ├── client/
>     └── server/
>         ├── config.yml
>         ├── models/
>         ├── server.py
>         ├── static/
>         │   ├── embs.npy
>         │   ├── images/
>         │   │   ├── 000000.jpg
>         │   │   ├── 000001.jpg
>         │   │   ├── ...
>         │   │   └── 999999.jpg
>         │   ├── imgs.npy
>         │   └── lbls.npy
>         └── utils.py
> ```
> 
> 此外，在执行时`python server.py`，请确保您处于`vlslice/vlslice/server/`并且不会意外调用诸如 之类的命令 `python server/server.py`。如果错误仍然存​​在，请尝试使用非常小的 k (<50) 运行。

Thank you very much for your patient answer. This error is caused by the wrong picture path
